print(r"NFC West       W   L  T")
print(r"-----------------------")
print(r"Seattle        13  3  0")
print(r"San Francisco  12  4  0")
print(r"Arizona        10  6  0")
print(r"St. Louis      7   9  0")
print(r"")
print(r"NFC North      W   L  T")
print(r"-----------------------")
print(r"Green Bay      8   7  1")
print(r"Chicago        8   8  0")
print(r"Detroit        7   9  0")
print(r"Minnesota      5  10  1")